### ISSUE TITLE
No overload matches this call? Typescript?

### ISSUE THREAD

**Issue by tester-at-bmi** [4teamwork/cypress-drag-drop#103]
Hi All,

I have some issues within my editor that i don't know how to solve. 

Hope someone can guide me in the right direction solving the following: 
`cy.get('div[data-testid="CHECKBOX"]').drag('#test', {
          source: {},
          target: { position: 'bottom' },
          force: false
        }
);`

I'm getting the following error within my editor:
`No overload matches this call.
  Overload 1 of 3, '(targetSelector: keyof HTMLElementTagNameMap, options?: Partial<ClickOptions & { source: ClickOptions; target: ClickOptions; }>): true', gave the following error.
    Argument of type '"#test"' is not assignable to parameter of type 'keyof HTMLElementTagNameMap'.`

Any ideas on how to get rid of the error above in the editor?

currently i'm getting rid of the errors by using `//@ts-ignore`

**Comment by klingenm** [comment]
Using the following versions
```
tests@1.0.0 ---/tests
├── @4tw/cypress-drag-drop@2.2.0
├── @testing-library/cypress@8.0.3
├── @types/node@18.0.0
├── @types/testing-library__cypress@5.0.9
├── cypress-file-upload@5.0.8
├── cypress@10.1.0
├── eslint-plugin-cypress@2.12.1
├── nanoid@4.0.0
└── typescript@4.7.4
```

I have the same issue;

```
The last overload gave the following error.
    Argument of type '{ position: string; force: true; }' is not assignable to parameter of type 'Partial<ClickOptions & { source: ClickOptions; target: ClickOptions; }>'.
      Object literal may only specify known properties, and 'position' does not exist in type 'Partial<ClickOptions & { source: ClickOptions; target: ClickOptions; }>'.

55       position: 'bottom',
         ~~~~~~~~~~~~~~~~~~

  node_modules/@4tw/cypress-drag-drop/index.d.ts:17:5
    17     drag(targetAlias: string, options?: Options): true
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.
```

**Comment by Mawster** [comment]
Hello,

it seems that the type definition is wrong. It is mentioned that 
"The options are directly passed to Cypress' trigger command. So, all options from https://docs.cypress.io/api/commands/trigger#Arguments are possible."

so ignoring the error helps and it gets passed, but the typedefinition of the options is false and does not include the https://docs.cypress.io/api/commands/trigger#Arguments and in that case you run in the issue with the "No overload matches this call."

**Comment by joPaquet02** [comment]
> Hi All,
> 
> I have some issues within my editor that i don't know how to solve.
> 
> Hope someone can guide me in the right direction solving the following: `cy.get('div[data-testid="CHECKBOX"]').drag('#test', { source: {}, target: { position: 'bottom' }, force: false } );`
> 
> I'm getting the following error within my editor: `No overload matches this call. Overload 1 of 3, '(targetSelector: keyof HTMLElementTagNameMap, options?: Partial<ClickOptions & { source: ClickOptions; target: ClickOptions; }>): true', gave the following error. Argument of type '"#test"' is not assignable to parameter of type 'keyof HTMLElementTagNameMap'.`
> 
> Any ideas on how to get rid of the error above in the editor?
> 
> currently i'm getting rid of the errors by using `//@ts-ignore`

Did you find a fix for this issue?

I'm having trouble with this issue aswell. 
I got the command like this in command.ts
`cy.get(sourceItem).drag(targetItem);`

From that command, my row did get move but to the position before the source because the default target is `top` and because of that the `sourceItem` get placed on the top of `targetItem` location.
If i add this to my command:
`cy.get(sourceItem).drag(targetItem, {source: {}, target: { position: 'bottom' }, force: false} );`
The pointer is `bottom` but cypress never triggered the `dataTransfer` of the item.
Can someone help me please.
