### ISSUE TITLE
Allow drag from a position within the element

### ISSUE THREAD

**Issue by technomage** [4teamwork/cypress-drag-drop#11]
We have elements that are sensitive to where the mouse down occurs within the element.  It would be nice to do the mouse down with more control (pixel offset, or position as in the drag input).

**Comment by bierik** [comment]
@technomage In #1 we are discussing a similar issue. What about having something like this https://github.com/4teamwork/cypress-drag-drop/issues/1#issuecomment-523966277

**Comment by bierik** [comment]
Please follow the discussion on #1
