### ISSUE TITLE
allow options, or documentation on how to use them

### ISSUE THREAD

**Issue by rocketsurgeonboic** [4teamwork/cypress-drag-drop#12]
Ex: element is covered, we want to force:true the drag event. How do we do it?

**Comment by bierik** [comment]
@rocketsurgeonboic Currently just the drop event is forced. It is not possible to pass an option to force the drag event.
Would something like this be helpful:
```javascript
cy.get('.sourceitem').drag('.targetitem', { force: true });
```
This would force all `dragstart`, `dragover` and `drop` events.

**Comment by bierik** [comment]
@rocketsurgeonboic The thing is, that there are three different events happening from `dragging` over `drag over` to `drop`. So when having an option like `force`, which event should be forced.

You are also saying that `element is covered`. So this means that the element you are trying to drag is covered by a different element. So a user using the interface would not be able to drag the element as well. So do you really need to force the `drag` event?

**Comment by bierik** [comment]
@rocketsurgeonboic I close this Issue because #16 is about the same Issue. Keep watching #16 for the fix.
