### ISSUE TITLE
Cypress 11 support

### ISSUE THREAD

**Issue by JohnnyFun** [4teamwork/cypress-drag-drop#121]
Looks like it might just be a matter of updating dependency expectations?

**Comment by dmaicher** [comment]
yeah indeed. I tried and it works just fine using Cypress 11

**Comment by JohnnyFun** [comment]
And sounds like they're about to release v12, fwiw, so might as well make it allow that version too: https://github.com/cypress-io/cypress/issues/7306#issuecomment-1314070767

**Comment by dmaicher** [comment]
Or maybe just allow any version? 😊

**Comment by JohnnyFun** [comment]
lol, I had the same thought right after I commented and saw your PR. Yeah, I'd honestly say we should just make a note in the readme like "Good on cypress@6-11, probably good on others after too..."

**Comment by vaibhavganatra** [comment]
@dmaicher Thank you merging the [PR122](https://github.com/4teamwork/cypress-drag-drop/pull/122).
Would you be able to create a new version release 2.2.2 which includes these changes?

**Comment by dmaicher** [comment]
@vaibhavganatra I did not merge the PR nor do I have the permission to do so.

**Comment by vaibhavganatra** [comment]
@bierik This is blocking us from upgrading to cypress 11.

**Comment by dmaicher** [comment]
> @bierik This is blocking us from upgrading to cypress 11.

@vaibhavganatra this package certainly is not preventing anyone from upgrading to Cypress 11. You could just [override](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) the peer requirement for example. I did the same for now until a new release is available.

**Comment by bierik** [comment]
@dmaicher @vaibhavganatra  Released `2.2.2` with cypress 11 support. Thank you so much for your contribution.

**Comment by vaibhavganatra** [comment]
> > @bierik This is blocking us from upgrading to cypress 11.
> 
> @vaibhavganatra this package certainly is not preventing anyone from upgrading to Cypress 11. You could just [override](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) the peer requirement for example. I did the same for now until a new release is available.

@bierik @dmaicher I really had no clue about the workaround to resolve dependencies. Thanks for providing a workaround for future use and for your contribution.
