### ISSUE TITLE
Cypress 12.0.2 not supported

### ISSUE THREAD

**Issue by wrengames** [4teamwork/cypress-drag-drop#127]
Hi,

Can you please update the `peerDependencies` to include cypress ^12.0.0?

Thanks,
Stu

**Comment by Barna-Molnar** [comment]
Hi, 
the same problem here as well, after migration to cypress v12 it does not work anymore 'cos of the above-mentioned issue.
Could you pls check and correct ASAP ?
thx 
Barni

**Comment by lvonlanthen** [comment]
@wrengames and @Barna-Molnar: Version `2.2.3` has been released, it supports Cypress 12.

**Comment by wrengames** [comment]
Thanks @lvonlanthen
