### ISSUE TITLE
Allow specifying a relative position parameter when dragging the source element.

### ISSUE THREAD

**Issue by henrygoodman** [4teamwork/cypress-drag-drop#133]
Hi,

I am trying to move an element which also has a resize option. As such, attempting to move the element by dragging from the top left corner (as it appears the move() command does per default) of the source element triggers the resize as opposed to moving the element. 

Ideally, I would like there to be an optional parameter to specify the position whereby the source element is dragged from (top left default, center option etc). 

If this is possible to consider at all, would appreciate it! Definitely helps when the element is intractable with different mousedown events in different areas.

**Comment by halfer** [comment]
Hiya @henrygoodman. Did you solve this? I see that you opened this ticket and then closed it shortly afterwards. I have a similar problem.
