### ISSUE TITLE
Element could've already been detached from the DOM when "mouseup" is triggered  

### ISSUE THREAD

**Issue by andriibuts** [4teamwork/cypress-drag-drop#14]
Trying to add a test for an app which uses [react-dnd](https://react-dnd.github.io) and in my case `drop target` node is removed from the DOM after the `drop` event is triggered.

At the time `mouseup` is triggered the node is no longer in the DOM and `cypress` returns an error.

```
CypressError: cy.trigger() failed because this element is detached from the DOM.
```

As I understand some implementations of DnD could listen for the `drop` event, some - for `mouseup` event and some for both.

According to the [cypress docs on conditional testing](https://docs.cypress.io/guides/core-concepts/conditional-testing.html#Definition) we can not implement a condition logic to checks if `drop target` node still exists in the DOM before triggering `mouseup` because it has been removed from the DOM asynchronously.

Can we update the command so it accepts another parameter `dropEvents` (with default value `["drop"]`) so a user can define specific event(s) to trigger?

On a separate note, not sure we need it to be an array.

If the proposed solution looks reasonable I can create a PR.

Full error:
```
CypressError: cy.trigger() failed because this element is detached from the DOM.

<div class="EmptyBlock_block__2auyt" data-cy="empty-block-placeholder" draggable="true"></div>

Cypress requires elements to be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.trigger()

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom

All 3 subject validations failed on this subject.
```

**Comment by arnabmondal19** [comment]
Hi, I am seeing similar kind of issues with "**mouseup**" when trying to execute multiple tests together. In my scenario i have 2 Columns and wanted to drag and drop components 2 different columns. 1st test passed (adding button to Column) during 2nd test (adding Icon to Column) it failed with while executing "**mouseup**". I can see the Icon has been added in Column but trigger event has failed.
NOTE: if i run only **Button** or **Icon** tests, it worked well. Failing when trying to run together.

 Can you please suggest why running multiple tests same time execution failed?

Multiple dnd failed:
![dnd single tests](https://user-images.githubusercontent.com/54146331/67423135-b400c580-f5a1-11e9-94c4-7a7261b86823.png)

![issue with dnd](https://user-images.githubusercontent.com/54146331/67422707-ff66a400-f5a0-11e9-8131-89fbe3872155.png)

Single Tests:
![dnd issue 2](https://user-images.githubusercontent.com/54146331/67422809-28873480-f5a1-11e9-8b83-5d853fc09c4e.png)

**Comment by bierik** [comment]
@arnabmondal19 I think your Issue could be fixed with the suggestion from @andriibuts.
@andriibuts I would really appreciate a PR to fix this Issue. So feel free to open a PR. Maybe you can simply wrap the `mouseup` event in a `try`-block so one does not have to specify if the element accepts a `drop` or `mouseup` event.

**Comment by bierik** [comment]
@andriibuts I made a PR here: https://github.com/4teamwork/cypress-drag-drop/pull/26
Could you please try out this fix with your setup. I did a test using vue-draggable trying to mimic the behavior you described.

**Comment by andriibuts** [comment]
@bierik, thanks for the PR, I've tried it on my setup and it seems to work fine now. 

Also, I left one question in the PR

**Comment by arnabmondal19** [comment]
@bierik - This fix did not solve my issue though. i am still seeing the issue. Running multiple tests.
