### ISSUE TITLE
Cypress Typescript error ts(2769)

### ISSUE THREAD

**Issue by Ixluxi** [4teamwork/cypress-drag-drop#141]
Hi,

I'm creating a new automation framework using TypeScript, Cypress v12.17.3, @4tw/cypress-drag-drop v2.2.4

The old framework uses JavaScript, Cypress v12.12.0, @4tw/cypress-drag-drop v2.2.3

In the old framework, this code works fine:

`		cy.get('div[id^="available-page"]')
		.eq(0)
		.drag('[order="1"] > .list-group', {
		  target: {
			position: 'center',
		  },
		});`

In the new framework, TypeScript complains:

"No overload matches this call.
  Overload 1 of 3, '(targetSelector: keyof HTMLElementTagNameMap, options?: Partial<ClickOptions & { source: ClickOptions | LocationOptions; target: ClickOptions | LocationOptions; }> | undefined): true', gave the following error.
    Argument of type '"[order=\"1\"] > .list-group"' is not assignable to parameter of type 'keyof HTMLElementTagNameMap'.
  Overload 2 of 3, '(targetSelector: string, options?: Partial<ClickOptions & { source: ClickOptions | LocationOptions; target: ClickOptions | LocationOptions; }> | undefined): true', gave the following error.
    Type '{ position: string; }' is not assignable to type 'ClickOptions | LocationOptions | undefined'.
      Object literal may only specify known properties, and 'position' does not exist in type 'ClickOptions | LocationOptions'.
  Overload 3 of 3, '(targetAlias: string, options?: Partial<ClickOptions & { source: ClickOptions | LocationOptions; target: ClickOptions | LocationOptions; }> | undefined): true', gave the following error.
    Type '{ position: string; }' is not assignable to type 'ClickOptions | LocationOptions | undefined'.
      Object literal may only specify known properties, and 'position' does not exist in type 'ClickOptions | LocationOptions'.ts(2769)"

I'm fairly certain that this is TypeScript being its usual difficult self, I was just wondering if you have any pointers on how I can resolve this issue?

To cover the basics, I have imported @4tw/cypress-drag-drop into my commands.ts file and added "@4tw/cypress-drag-drop" to my tsconfig's compilerOptions > types array.

**Comment by nzrii-kysel** [comment]
The type definition is incomplete.
Pasting this into `index.d.ts`  inside `cypress` folder will fix the issue:
```
type LocationOptions = {
  x: number
  y: number
}

type DragElementOptions = Cypress.ClickOptions | LocationOptions | {
  position: Cypress.PositionType
}

type DragOptions = Partial<Cypress.ClickOptions & {
  source: DragElementOptions
  target: DragElementOptions
}>

declare namespace Cypress {
  interface Chainable {
    drag<K extends keyof HTMLElementTagNameMap>(targetSelector: K, options?: DragOptions): Chainable<boolean>
    drag<E extends Node = HTMLElement>(targetSelector: E, options?: DragOptions): Chainable<boolean>
    drag(targetAlias: string, options?: DragOptions): Chainable<boolean>
  }
}
```
