### ISSUE TITLE
cypress 13 support

### ISSUE THREAD

**Issue by hooman-mirghasemi** [4teamwork/cypress-drag-drop#144]
please add cypress 13 support to your plugin

when i update to cypress 13 by running npm install i see this error:

Could not resolve dependency:
npm WARN peer cypress@"^2.1.0 || ^3.1.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0" from @4tw/cypress-drag-drop@2.2.4

**Comment by lvonlanthen** [comment]
Version `2.2.5` with support for Cypress 13.x was released just now.
