### ISSUE TITLE
Do I need to define DataTransfer()?

### ISSUE THREAD

**Issue by Jaguirre123** [4teamwork/cypress-drag-drop#15]
<img width="1233" alt="Screen Shot 2019-11-13 at 3 23 41 PM" src="https://user-images.githubusercontent.com/35276012/68813095-974c3080-0629-11ea-8dcc-cf0ff6509bfa.png">

**Comment by Jaguirre123** [comment]
Is it possible to add better documentation?

**Comment by bierik** [comment]
@Jaguirre123 which version of the plugin are you using (lookup in the `package.lock` or `yarn.lock` file)?

**Comment by Jaguirre123** [comment]
@bierik @4tw/cypress-drag-drop@1.3.0

**Comment by bierik** [comment]
@Jaguirre123 I am not able to reproduce your error with 1.3.0
How did you install the plugin? What version of cypress are you using?

**Comment by alexisbssn** [comment]
I was able to reproduce with 1.3.1 and cypress 3.8.2

**Comment by bierik** [comment]
Unrelated to this repo
