### ISSUE TITLE
This element is not visible because of parent

### ISSUE THREAD

**Issue by 90sidort** [4teamwork/cypress-drag-drop#16]
Hi, 

I am trying to use drag and drop in tests but it fails:
![image](https://user-images.githubusercontent.com/55019396/69226504-8a2ac680-0b80-11ea-8666-eae70d149733.png)

I added {force: true} to all triggers but the error still occurs. Where should I add {force: true} to disable error checking?

**Comment by bierik** [comment]
@90sidort The drag'n'drop operation is done in three steps:

1. Grabbing the item (using 'mousedown' and `drag`)
2. Moving the item (using `dragover`)
3. Dropping the item (using `mouseup` and `drop`)

It's currently not possible to pass the force option to all the events needed to perform the drag'n'drop operation. I will fix this and inform you when it's done.

**Comment by sorayaM** [comment]
@bierik have these changes been implemented?
