### ISSUE TITLE
Plugin don't work as expected with Angular material

### ISSUE THREAD

**Issue by jmcollin78** [4teamwork/cypress-drag-drop#24]
I've tried many workaround to make drag and drop work with Cypress (ie your drag and drop plugin also) but the only working solution is here : https://stackoverflow.com/questions/55361499/how-to-implement-drag-and-drop-in-cypress-test see @Bkucera solution.

Maybe it's a good idea to integrate his solution in this plugin ?

**Comment by bierik** [comment]
@jmcollin78 I have never worked with Angular nor Angular material. We also do not use Angular at all in the company. So I probably wont have too much time to solve that issue. But feel free to open a PR. I am also doing a review.

**Comment by yglin** [comment]
This code snippet works for me, inspired by @jmcollin78 's [stackflow post](https://stackoverflow.com/questions/55361499/how-to-implement-drag-and-drop-in-cypress-test) and [official recipe](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__drag-drop/cypress/integration/drag_n_drop_spec.js)

```
Cypress.Commands.add(
  'dragTo',
  { prevSubject: 'element' },
  (subject, droppableSelector: string) => {
    const coords = Cypress.$(droppableSelector)[0].getBoundingClientRect();
    cy.wrap(subject)
      .trigger('mousedown', { which: 1 })
      .trigger('mousemove', { clientX: coords.x + 10, clientY: coords.y + 10 })
      .trigger('mouseup', { force: true });
  }
);

```

Usage: 

`cy.get('.selector-for-draggable-element').dragTo('.selector-for-droppable-element');`
