### ISSUE TITLE
Support for vue-draggable

### ISSUE THREAD

**Issue by nolanpro** [4teamwork/cypress-drag-drop#3]
Thanks for this plugin! Any chance we can get support for vue-draggable like this PR is attempting to do (but hasn't gotten much traction in the cypress repo) https://github.com/cypress-io/cypress-example-recipes/pull/204. Thanks!

**Comment by bierik** [comment]
@nolanpro Glad you like it! I'm running https://www.npmjs.com/package/vuedraggable in production, which is based on sortable.js. The tests are working fine with the plugin.
The sortable.js also uses native drag'n'drop. So I don't really know what the difference to https://github.com/Vivify-Ideas/vue-draggable is. Maybe you have any hints what the problem could be or you may try out https://www.npmjs.com/package/vuedraggable instead.

**Comment by nolanpro** [comment]
Thanks for the reply. I'm going to play with this some more any if needed I'll come up with a minimal example. Thanks!
