### ISSUE TITLE
elements found but no action was performed

### ISSUE THREAD

**Issue by sorayaM** [4teamwork/cypress-drag-drop#31]
I read about the commits that you made about the force : true, but still even though the elements were being found, no action was performed, they remained where they were....

**Comment by Prophetaa** [comment]
What's happening to me is, it picks the element and it disappears, never goes to the target position

**Comment by sorayaM** [comment]
I've since found out that it has something to do with the Angular components and so....
has there been any findings regarding this issue? is there a way to interact with such elements?

**Comment by Prophetaa** [comment]
I have found nothing yet, but I will keep you up-to-date, what version of Angular are you using @sorayaM   ?

**Comment by sorayaM** [comment]
@Prophetaa Angular 7

**Comment by bierik** [comment]
@sorayaM There is already an open thread on https://github.com/4teamwork/cypress-drag-drop/issues/24 about the angular integration. Can we close this issue?

**Comment by sorayaM** [comment]
@bierik the solution was for protractor, and it tried to translate it to cypress, but didn't work. We can close this anyhow, since cypress may be working on the solution for this elements

**Comment by bierik** [comment]
Okay then. Thank you @sorayaM .
