### ISSUE TITLE
cy.get(...).move is not a function

### ISSUE THREAD

**Issue by sauvai** [4teamwork/cypress-drag-drop#36]
I can use cy.get(...).drag but not cy.get(...).move, am i missing something ?
I use it like this :

` cy.get(".titleBlock").move("center");`

**Comment by hankolsen** [comment]
Same thing for me

**Comment by ishanshukla97** [comment]
This repository (v1.3.1) has the latest code with move() implemented. But npm installing the same version doesn't give us the latest code. In it .move() is not implemented.
What could be the issue?

**Comment by armno** [comment]
it seems `.move()` is a new feature from #27 and was added after v.1.3.1 released (702d7818a882011329ab655fcd66e7f9b5b0f4e4).

a workaround for me is to install this module from github directly:

```sh
npm uninstall --save-de @4tw/cypress-drag-drop
npm install --save-dev 4teamwork/cypress-drag-drop
```

there should be something like this in `package.json`

```diff
"devDependencies": {
-      "@4tw/cypress-drag-drop": "^1.3.1",
+      "@4tw/cypress-drag-drop": "github:4teamwork/cypress-drag-drop",
```

until we get a new release on npm. hope it helps 🤞

**Comment by skivol** [comment]
@bierik, so what about new release which includes `move` command ? 😃

**Comment by bierik** [comment]
@skivol New release 1.4.0 includes the new move command

**Comment by skivol** [comment]
@bierik, great ! Thank you ! :)
