### ISSUE TITLE
Installing causes cy to not be recognized?

### ISSUE THREAD

**Issue by CScharer** [4teamwork/cypress-drag-drop#46]
Does this work with Cypress 5.6.0?
I installed the latest package and after installing it I get an error that it no longer recognized cy.

**Comment by RosenMihaylov** [comment]
Hello, 

I`m a cypress tester and I`m using your plugin for more than 6 months. When Cypress updated to version 5.0.0 I tried updated your plugin to version 1.4.0 but It didn` t work. I shows the action as command, but never moved the element. 

After several attempts i returned to version 1.3.1 and Cypress 5.6.0.

**Comment by bierik** [comment]
@CScharer @RosenMihaylov I updated all devDependencies and installed cypress as a devDependency itself to test the plugin against a specific version (6.x). With cypress 6.x all the tests are passing. Could you try again with master please.

**Comment by CScharer** [comment]
@RosenMihaylov Since the test I was trying to automate was an edge case and would not give a good ROI I no longer need this plugin.

**Comment by RosenMihaylov** [comment]
Nope, still not working for me. Test initializes the action but never does it with version drag-drop 1.4, cypress 6.1, but combination drag-drop 1.3.1, cypress 6.1 still works perfectly

![image](https://user-images.githubusercontent.com/58471905/102778441-3f8b0780-439b-11eb-87ea-f0479af33f92.png)
