### ISSUE TITLE
Will a new version be published on NPM?

### ISSUE THREAD

**Issue by rlingineni** [4teamwork/cypress-drag-drop#51]
@bierik / @Sauloxd - we are relying on this package, and it seems that it was updated recently to support other peer versions of Cypress, but the version on npm still seems to be `1.4.0`. 

Could you publish this package?

This is causing errors for us:
![image](https://user-images.githubusercontent.com/5509813/103362406-13e4dd00-4a7f-11eb-9ec2-a586b0920933.png)

https://github.com/4teamwork/cypress-drag-drop/blob/089669c3a2c9a4c94a47d4a7532776339fd0e661/package.json#L48

 Thank you for writing and maintaining this!

**Comment by bierik** [comment]
@rlingineni I just released 1.5.0 with the latest changes: https://www.npmjs.com/package/@4tw/cypress-drag-drop
