### ISSUE TITLE
Coordinates can be passed into drag function but are ignored

### ISSUE THREAD

**Issue by silentchaostheory** [4teamwork/cypress-drag-drop#57]
If you review the documentation for the trigger command, the options that can be passed in include coordinates from the top, left corner of the subject element where the pointer/mouse is located when the down/up/move/etc action is performed. 
https://docs.cypress.io/api/commands/trigger.html#Coordinates

The drag being called on the row in the relative location of the drag handle:
` cy.get(studyAct.studyactmillercontainer) // container for all of the rows in the miller column
      .should('be.visible')
      .find(studyAct.studyactmillerrow) // gets a list of all of the rows in the container
      .then($rows => {
        cy.wrap($rows).last().as('there') // alias for the last row in the list of rows
        cy.wrap($rows)
          .contains(studyAct.studyactmillerrow, 'Adverse Events') // gets a specific row based on the label text
          .focus()
// 28, 18 is the relative location of the center of the reorder-icon that is the handle used to trigger the drag for the row element; it must be clicked to drag the row element. when using the .find('.reorder-icon') for the .drag command, the parent row is not moved
          .drag('@there', 28, 18, { force: true })
          .wait('@graphql')
// this request is not triggered
        cy.get('.v-progress-linear.loader').should('not.be.visible')
      })`
![image](https://user-images.githubusercontent.com/56895341/110365725-ff870880-800a-11eb-9a84-5963a1e7dac3.png)

The drag being called on the drag handle:
`    cy.get(studyAct.studyactmillercontainer)
      .should('be.visible')
      .find(studyAct.studyactmillerrow)
      .then($rows => {
        cy.wrap($rows).filter(':visible').last().as('there')
        cy.wrap($rows)
          .contains(studyAct.studyactmillerrow, 'Adverse Events')
          .focus()
          .find('.reorder-icon')
          .drag('@there', { force: true })
          .wait('@graphql')
        cy.get('.v-progress-linear.loader').should('not.be.visible')
      })`
      
![image](https://user-images.githubusercontent.com/56895341/110365542-c484d500-800a-11eb-8c8e-7ad6cb39ad81.png)

There should be an object, and documentation on the use of the object. for passing in x,y coordinates for the trigger commands to use on triggering mouse/pointer ON a location. There should also be a separate object for use in moving TO a specific location.

**Comment by silentchaostheory** [comment]
Forgot to provide version information, apologies:
  "dependencies": {
...
    "cypress": "^4.3.0",
 ...
  "devDependencies": {
    "@4tw/cypress-drag-drop": "^1.4.0",
...

**Comment by silentchaostheory** [comment]
Tried replacing this: 
`      cy.wrap($browseSectionsContainer)
        .find(selectors.artifactsTableAccordion)
        .children('button')
        .drag(selectors.relationshipsTableAccordion, { force: true, position: 'center' })`
With this:
`cy.wrap($browseSectionsContainer)
        .find(selectors.artifactsTableAccordion)
        // .children('button')
        .drag(selectors.relationshipsTableAccordion, { x: 745, y: 33 })`
And it worked great. The child button isn't visible so being able to use the button's center offset instead of the button allows us to avoid using { force: true }; it's a good thing.

**Comment by bierik** [comment]
As soon as https://github.com/4teamwork/cypress-drag-drop/pull/78 is merged, it'll land in a new release.
