### ISSUE TITLE
Add Cypress 7.1.0 support

### ISSUE THREAD

**Issue by yuriidrapak** [4teamwork/cypress-drag-drop#62]

**Comment by mbranicky** [comment]
@yuriidrapak could you please merge the attached PR into main branch? Is there any technical reason to not do that? We appreciate your plugin in the team very much and use it quite a lot. Currently it's the only dependency which stops us to update to Cypress 7.x.

**Comment by lvonlanthen** [comment]
@yuriidrapak and @mbranicky With version 1.7.0 released today, Cypress 7.x is now suppported.
