### ISSUE TITLE
Can not install with cypress 7.0 or above

### ISSUE THREAD

**Issue by pstema** [4teamwork/cypress-drag-drop#74]
I get this error when running
npm install --save-dev @4tw/cypress-drag-drop

Could not resolve dependency:
npm ERR! peer cypress@"^2.1.0 || ^3.1.0 || ^4.0.0 || ^5.0.0 || ^6.0.0" from @4tw/cypress-drag-drop@1.6.0

Looks like the update was made but not published

as of 7/20/2021
cypress is now on version 8!

**Comment by lvonlanthen** [comment]
@pstema With version 1.8.0 released today, Cypress 8.x is now supported.
