### ISSUE TITLE
How to use this library with typescript

### ISSUE THREAD

**Issue by dauledk** [4teamwork/cypress-drag-drop#8]
My `commands.ts` is a typescript file.

When I add the line `require('cypress-drag-drop');`, I get this error: 

```
Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.ts(2580)
```

How can I solve this problem?

**Comment by bierik** [comment]
I am not a typescript expert. And I don't think this is a problem with cypress.
But maybe this will help you: https://stackoverflow.com/a/35961176/4558231.
So in my understanding, you simply need to do `npm install @types/node --save-dev`
